import {
  Bank,
  Book,
  Buildings,
  Calendar,
  Car,
  Certificate,
  ChartBar,
  ChartPie,
  ClipboardText,
  CurrencyDollar,
  FileIcon,
  FileText,
  FirstAid,
  Gavel,
  Headset,
  Robot,
  Shield,
  Truck,
  User,
  Users,
} from '@phosphor-icons/react';

export const modules = [
  {
    id: 'agfolhaweb',
    title: 'AgFolhaWeb',
    subtitle: 'Sistema de Folha de Pagamento',
    Icon: Users,
    status: 'online',
    lastAccess: 'Hoje, 08:30',
  },
  {
    id: 'agfrota',
    title: 'AgFrota',
    subtitle: 'Sistema de Frota de Veículos',
    Icon: Car,
    status: 'online',
    lastAccess: 'Ontem, 14:20',
  },
  {
    id: 'aggpt-adm',
    title: 'AgGPT - ADM',
    subtitle: 'Sistema Administrador da I.A Ágape',
    Icon: Robot,
    status: 'online',
    lastAccess: 'Hoje, 10:15',
  },
  {
    id: 'agobra',
    title: 'AgObra',
    subtitle: 'Sistema de Gestão de Obras',
    Icon: Buildings,
    status: 'online',
    lastAccess: 'Semana passada',
  },
  {
    id: 'agalvara',
    title: 'AgAlvará',
    subtitle: 'Sistema de Validação de Alvará',
    Icon: Certificate,
    status: 'online',
    lastAccess: 'Hoje, 09:00',
  },
  {
    id: 'agcertidao',
    title: 'AgCertidao',
    subtitle: 'Sistema de Certidões',
    Icon: FileIcon,
    status: 'online',
    lastAccess: 'Ontem, 16:30',
  },
  {
    id: 'agcontrato',
    title: 'AgContrato',
    subtitle: 'Sistema de Gestão de Contratos',
    Icon: ClipboardText,
    status: 'online',
    lastAccess: 'Hoje, 11:20',
  },
  {
    id: 'agdiario',
    title: 'AgDiario',
    subtitle: 'Sistema de Diário Oficial',
    Icon: Book,
    status: 'online',
    lastAccess: 'Hoje, 07:45',
  },
  {
    id: 'agatendimento',
    title: 'AgAtendimento',
    subtitle: 'Sistema de Atendimento Eletrônico',
    Icon: Headset,
    status: 'online',
    lastAccess: 'Ontem, 15:10',
  },
  {
    id: 'agconsig',
    title: 'AgConsig',
    subtitle: 'Sistema de Criação para Crédito Consignado',
    Icon: CurrencyDollar,
    status: 'online',
    lastAccess: 'Hoje, 13:25',
  },
  {
    id: 'agadministrador',
    title: 'AgAdministrador',
    subtitle: 'Administrador do Portal',
    Icon: Shield,
    status: 'online',
    lastAccess: 'Hoje, 08:00',
  },
  {
    id: 'agcamara',
    title: 'AgCamara',
    subtitle: 'Administrador dos Sites da Câmara',
    Icon: Buildings,
    status: 'online',
    lastAccess: 'Ontem, 17:00',
  },
  {
    id: 'agcontracheque',
    title: 'AgContraCheque',
    subtitle: 'Contra-Cheque on-line',
    Icon: FileText,
    status: 'online',
    lastAccess: 'Hoje, 12:00',
  },
  {
    id: 'agconvenio',
    title: 'AgConvenio',
    subtitle: 'Sistema de Convênios e Contratos',
    Icon: ClipboardText,
    status: 'online',
    lastAccess: 'Ontem, 14:30',
  },
  {
    id: 'agdoc',
    title: 'AgDOC',
    subtitle: 'Gestão de Documentos',
    Icon: FileIcon,
    status: 'online',
    lastAccess: 'Hoje, 09:45',
  },
  {
    id: 'agdam',
    title: 'AgDAM',
    subtitle: '2ª Via DAM',
    Icon: FileText,
    status: 'online',
    lastAccess: 'Ontem, 11:15',
  },
  {
    id: 'agfolhaclient',
    title: 'AgFolhaClient',
    subtitle: 'Sistema de Gestão de Pessoas',
    Icon: Users,
    status: 'online',
    lastAccess: 'Hoje, 10:30',
  },
  {
    id: 'agendamento',
    title: 'Agendamento',
    subtitle: 'Sistema de Agendamento',
    Icon: Calendar,
    status: 'online',
    lastAccess: 'Ontem, 13:45',
  },
  {
    id: 'agfideliza',
    title: 'AgFideliza',
    subtitle: 'Sistema de Fidelização',
    Icon: Users,
    status: 'online',
    lastAccess: 'Hoje, 14:20',
  },
  {
    id: 'aggestor',
    title: 'AgGestor',
    subtitle: 'Sistema de Contabilidade Pública',
    Icon: ChartBar,
    status: 'online',
    lastAccess: 'Ontem, 16:00',
  },
  {
    id: 'agin',
    title: 'AGIN',
    subtitle: 'Gestão Integrada de Negócios',
    Icon: ChartPie,
    status: 'online',
    lastAccess: 'Hoje, 08:15',
  },
  {
    id: 'agissbanco',
    title: 'AglssBanco',
    subtitle: 'ISS Banco',
    Icon: Bank,
    status: 'online',
    lastAccess: 'Ontem, 15:30',
  },
  {
    id: 'aglicitacao',
    title: 'AgLicitação',
    subtitle: 'Sistema de Licitação',
    Icon: Gavel,
    status: 'online',
    lastAccess: 'Hoje, 11:00',
  },
  {
    id: 'aglogistica',
    title: 'AgLogistica',
    subtitle: 'Compras, Almoxarifado e Patrimônio',
    Icon: Truck,
    status: 'online',
    lastAccess: 'Ontem, 14:00',
  },
  {
    id: 'agpatri',
    title: 'AgPatri',
    subtitle: 'Sistema de Controle Patrimonial',
    Icon: Buildings,
    status: 'online',
    lastAccess: 'Hoje, 10:00',
  },
  {
    id: 'agportal',
    title: 'AgPortaIServidorWeb',
    subtitle: 'Portal do Servidor',
    Icon: Shield,
    status: 'online',
    lastAccess: 'Ontem, 12:30',
  },
  {
    id: 'agprotocolo',
    title: 'AgProtocolo',
    subtitle: 'Sistema de Gestão de Protocolo',
    Icon: FileText,
    status: 'online',
    lastAccess: 'Hoje, 09:30',
  },
  {
    id: 'agrecadastramento',
    title: 'AgRecadastramento',
    subtitle: 'Módulo de Recadastramento de Servidores',
    Icon: User,
    status: 'online',
    lastAccess: 'Ontem, 17:30',
  },
  {
    id: 'agrh',
    title: 'AgRH',
    subtitle: 'Sistema de Recursos Humanos',
    Icon: User,
    status: 'online',
    lastAccess: 'Hoje, 08:45',
  },
  {
    id: 'agsagres',
    title: 'AgSagres',
    subtitle: 'Sistema de Prestação de Contas',
    Icon: ChartBar,
    status: 'online',
    lastAccess: 'Ontem, 16:45',
  },
  {
    id: 'agsaude',
    title: 'AgSaúde',
    subtitle: 'Sistema de Saúde',
    Icon: FirstAid,
    status: 'online',
    lastAccess: 'Hoje, 13:00',
  },
  {
    id: 'agsiap',
    title: 'AgSIAP',
    subtitle: 'Sistema de geração arquivo SIAP',
    Icon: FileText,
    status: 'online',
    lastAccess: 'Ontem, 15:00',
  },
  {
    id: 'agsocial',
    title: 'AgSocial',
    subtitle: 'Sistema de Ação Social',
    Icon: Users,
    status: 'online',
    lastAccess: 'Hoje, 11:45',
  },
  {
    id: 'agtransparencia',
    title: 'AgTransparencia',
    subtitle: 'Sistema de Transparência',
    Icon: Shield,
    status: 'online',
    lastAccess: 'Ontem, 14:15',
  },
  {
    id: 'agtributos',
    title: 'AgTributos',
    subtitle: 'Sistemas de Tributos',
    Icon: CurrencyDollar,
    status: 'online',
    lastAccess: 'Hoje, 10:45',
  },
  {
    id: 'agtreinamento',
    title: 'AgTreinamento',
    subtitle: 'Vídeos de Treinamento de Sistemas',
    Icon: Users,
    status: 'online',
    lastAccess: 'Ontem, 13:00',
  },
  {
    id: 'agusuarios',
    title: 'AgUsuarios',
    subtitle: 'Cadastro de Usuários',
    Icon: User,
    status: 'online',
    lastAccess: 'Hoje, 08:00',
  },
  {
    id: 'agcemiterio',
    title: 'Cemitério',
    subtitle: 'Sistema de Cemitério',
    Icon: Buildings,
    status: 'online',
    lastAccess: 'Ontem, 16:20',
  },
  {
    id: 'e-gin',
    title: 'E-GIN',
    subtitle: 'Gestão Integrada de Negócios',
    Icon: ChartPie,
    status: 'online',
    lastAccess: 'Hoje, 12:30',
  },
];
